apiVersion: batch/v1
kind: Job
metadata:
  name: seed-products
  namespace: ecommerce
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed-products
          image: your-dockerhub-username/ecommerce-backend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          command: ["/bin/sh", "-c"]
          args:
            - python manage.py migrate && python manage.py loaddata products
